version: "3"

services:
  django_backend1:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app # maps project's app directory to docker's app directory
                     # this provides real time updates of our project
    command: >
      sh -c "python3 manage.py runserver 0.0.0.0:8000"